<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>ProfiC.Cli</RootNamespace>
    <AssemblyName>profi-c</AssemblyName>
    <Description>The profi-c command line driver.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProfiC.Compiler\ProfiC.Compiler.csproj" />
    <ProjectReference Include="..\ProfiC.Interpreter\ProfiC.Interpreter.csproj" />
  </ItemGroup>

</Project>
