using System.Text;
using ProfiC.Compiler.Lexing;

namespace ProfiC.Compiler.Semantics;

/// <summary>
/// <para>Every word the language owns, in a form something outside this repository can read.
/// </para>
/// <para>A TextMate grammar, a language server, or a highlighter for another editor all need
/// the same list, and all of them live where the compiler is not. Publishing it as a file means
/// a keyword is added in one place and the tooling notices, rather than the tooling being built
/// against the compiler and every keyword becoming a two-repository change.</para>
/// <para>Read from <see cref="ReservedWords"/> and <see cref="BuiltIns"/> directly rather than
/// listed again here. A second list would be a second thing to keep true, which is the failure
/// this exists to prevent.</para>
/// </summary>
public static class Vocabulary
{
    /// <summary>
    /// <para>The vocabulary as JSON, ordered and formatted so a diff shows what changed.</para>
    /// <para>Written by hand rather than through a serializer so the shape is settled here and
    /// visible: a consumer reads the field names, and nothing about them should depend on a
    /// serializer's defaults.</para>
    /// </summary>
    public static string AsJson()
    {
        StringBuilder json = new();

        json.AppendLine("{");
        json.AppendLine("  \"note\": \"Generated by 'pc vocabulary'. Do not edit by hand.\",");
        json.AppendLine();

        AppendList(json, "reservedWords", ReservedWords.Keywords.Keys, last: false);
        AppendList(json, "typeNames", BuiltIns.AllTypeNames, last: true);

        json.Append('}');

        return json.ToString();
    }

    private static void AppendList(
        StringBuilder json,
        string name,
        IEnumerable<string> words,
        bool last)
    {
        string[] sorted = [.. words.OrderBy(word => word, StringComparer.Ordinal)];

        json.AppendLine($"  \"{name}\": [");

        for (int i = 0; i < sorted.Length; i++)
        {
            json.Append($"    \"{sorted[i]}\"");
            json.AppendLine(i == sorted.Length - 1 ? string.Empty : ",");
        }

        json.AppendLine(last ? "  ]" : "  ],");

        if (!last)
        {
            json.AppendLine();
        }
    }
}
