name: CI (Linux)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build and test
    uses: ./.github/workflows/build.yml
    with:
      os: ubuntu-latest
